### ISSUE TITLE
Multi-touch

### ISSUE THREAD

**Issue by tch399** [iryan2/react-panel-transition#1]
Sorry to bother iryan2, I was reading a message you left a year ago about the multi-touch karabiner functionality on macos sierra, were you ever able to find an answer to this, in other words how to make the trackpad + F/D work?

Thanks.

**Comment by iryan2** [comment]
Ha, this is a funny way to get in touch, made me smile.

Sadly, no. I've tried to find a solution with BetterTouchTool but no luck. Never got any response from the Karabiner maintainers either :(

I had some dope customisations too, enter and backspace on touch+a and touch+q respectively. Miss it every day.

Let me know if you find a solution!
